// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentraSence.Api.Data;

#nullable disable

namespace SentraSence.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505212045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentraSence.Api.Models.AiAnalysis", b =>
                {
                    b.Property<Guid>("AiAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AlertThreshold")
                        .HasColumnType("float");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AudioClipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<int>("InferenceMs")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawOutputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoundCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiAnalysisId");

                    b.HasIndex("AudioClipId");

                    b.ToTable("AiAnalyses");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AlarmEvent", b =>
                {
                    b.Property<Guid>("AlarmEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlarmEventId");

                    b.HasIndex("UserId");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AlarmLocation", b =>
                {
                    b.Property<Guid>("AlarmLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("float");

                    b.Property<Guid>("AlarmEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.HasKey("AlarmLocationId");

                    b.HasIndex("AlarmEventId");

                    b.ToTable("AlarmLocations");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AudioClip", b =>
                {
                    b.Property<Guid>("AudioClipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlarmEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AudioClipId");

                    b.HasIndex("AlarmEventId");

                    b.HasIndex("UserId");

                    b.ToTable("AudioClips");
                });

            modelBuilder.Entity("SentraSence.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlarmEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrustedContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("AlarmEventId");

                    b.HasIndex("TrustedContactId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SentraSence.Api.Models.TrustedContact", b =>
                {
                    b.Property<Guid>("TrustedContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrustedContactId");

                    b.HasIndex("UserId");

                    b.ToTable("TrustedContacts");
                });

            modelBuilder.Entity("SentraSence.Api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AiAnalysis", b =>
                {
                    b.HasOne("SentraSence.Api.Models.AudioClip", "AudioClip")
                        .WithMany("Analyses")
                        .HasForeignKey("AudioClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioClip");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AlarmEvent", b =>
                {
                    b.HasOne("SentraSence.Api.Models.User", "User")
                        .WithMany("AlarmEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AlarmLocation", b =>
                {
                    b.HasOne("SentraSence.Api.Models.AlarmEvent", "AlarmEvent")
                        .WithMany("Locations")
                        .HasForeignKey("AlarmEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmEvent");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AudioClip", b =>
                {
                    b.HasOne("SentraSence.Api.Models.AlarmEvent", "AlarmEvent")
                        .WithMany("AudioClips")
                        .HasForeignKey("AlarmEventId");

                    b.HasOne("SentraSence.Api.Models.User", "User")
                        .WithMany("AudioClips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SentraSence.Api.Models.Notification", b =>
                {
                    b.HasOne("SentraSence.Api.Models.AlarmEvent", "AlarmEvent")
                        .WithMany("Notifications")
                        .HasForeignKey("AlarmEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentraSence.Api.Models.TrustedContact", "TrustedContact")
                        .WithMany()
                        .HasForeignKey("TrustedContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlarmEvent");

                    b.Navigation("TrustedContact");
                });

            modelBuilder.Entity("SentraSence.Api.Models.TrustedContact", b =>
                {
                    b.HasOne("SentraSence.Api.Models.User", "User")
                        .WithMany("TrustedContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AlarmEvent", b =>
                {
                    b.Navigation("AudioClips");

                    b.Navigation("Locations");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SentraSence.Api.Models.AudioClip", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("SentraSence.Api.Models.User", b =>
                {
                    b.Navigation("AlarmEvents");

                    b.Navigation("AudioClips");

                    b.Navigation("TrustedContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
